### ISSUE TITLE
TypeError: n is not a function - prelodr.min.js

### ISSUE THREAD

**Issue by mozgbrasil** [joseluisq/prelodr#24]
Hi! Good afternoon, my friend.

I'm using your library in a Magento project

And I would like to notify you of an error, I believe that some conflict

Access this url

http://magento-12167-48796-126866.cloudwaysapps.com/accessories/eyewear.html

See in firebug that the error is displayed

TypeError: n is not a function - prelodr.min.js (line 2, col 1184)

Do you know of any procedure to correct this occurrence

**Comment by joseluisq** [comment]
Hi,
This is because Prelodr v2 has two dependencies: https://github.com/joseluisq/prelodr/blob/master/bower.json#L26-L28
Checkout this example in browser: http://cdpn.io/rVeyXY

Your need to use Prelodr in browser you need bundle Prelodr and dependencies. For example using Webpack, Browserify or simply joining all files in one.

Anyway, I'll bundle all files soon (`prelodr.bundle.js`) 😄

**Comment by mozgbrasil** [comment]
Thank you my friend

Have a great weekend

**Comment by joseluisq** [comment]
@mozgbrasil done!
Please check out https://github.com/joseluisq/prelodr/releases/tag/v2.0.1
If you have some issue in the future feel free to send it.
